version: '3.1'

services:
  db:
    image: mariadb:10-bionic
    env_file: .env
    environment:
      MYSQL_HOST:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - 3306:3306
    restart: always
